version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-TrainIT
    environment:
      POSTGRES_USER: TrainIT
      POSTGRES_PASSWORD: TrainIT
      POSTGRES_DB: nest
    ports:
      - 5499:5432