[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/netlify"
  status = 200

[functions]
  external_node_modules = ["@nestjs/core", "@nestjs/common", "@nestjs/platform-express"]